In [3]:
import pandas as pd
import matplotlib.pyplot as plt 
import graphviz
import numpy as np
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix

In [25]:
pd1 = pd.read_csv('censustrain.csv', delimiter=';')
pd1.head()

age  Private  Self-emp-not-inc  Self-emp-inc  Federal-gov  Local-gov  \
0   39        0                 0             0            0          0   
1   50        0                 1             0            0          0   
2   38        1                 0             0            0          0   
3   53        1                 0             0            0          0   
4   28        1                 0             0            0          0   

   State-gov  Without-pay  fnlwgt  education-num   ...     Nicaragua  \
0          1            0   77516             13   ...             0   
1          0            0   83311             13   ...             0   
2          0            0  215646              9   ...             0   
3          0            0  234721              7   ...             0   
4          0            0  338409             13   ...             0   

    Scotland   Thailand   Yugoslavia   El-Salvador   Trinadad&Tobago   Peru  \
0          0          0            0             0                 0      0   
1          0          0            0             0                 0      0   
2          0          0            0             0                 0      0   
3          0          0            0             0                 0      0   
4          0          0            0             0                 0      0   

    Hong   Holand-Netherlands  income  
0      0                    0       0  
1      0                    0       0  
2      0                    0       0  
3      0                    0       0  
4      0                    0       0  

[5 rows x 88 columns]

In [26]:
X1 = pd1.iloc[:,0:-1].values.tolist()
print(X1[:5])
Y1 = pd1.iloc[:,-1].values.tolist()
print(Y1[:5])

[[39, 0, 0, 0, 0, 0, 1, 0, 77516, 13, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2174, 0, 40, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [50, 0, 1, 0, 0, 0, 0, 0, 83311, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [38, 1, 0, 0, 0, 0, 0, 0, 215646, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [53, 1, 0, 0, 0, 0, 0, 0, 234721, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [27]:
#Cross #Cross validation training DTL
clf1 = tree.DecisionTreeClassifier()
scores = cross_val_score(clf1, X1, Y1, cv=10)
print("Akurasi: %f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Akurasi: 0.817020 (+/- 0.01)


In [28]:
#Cross validation training MLP
clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15, 2), random_state=1)
scores = cross_val_score(clf2, X1, Y1, cv=10)
print("Akurasi: %f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Akurasi: 0.759190 (+/- 0.00)


In [29]:
#Split data 90%/10%
X_train, X_test, Y_train, Y_test = train_test_split(X1, Y1, test_size=0.1, random_state=42)
print(X_train[:5])
print(X_test[:5])

[[35, 1, 0, 0, 0, 0, 0, 0, 189916, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [20, 1, 0, 0, 0, 0, 0, 0, 284737, 10, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 20, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [34, 1, 0, 0, 0, 0, 0, 0, 37380, 9, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [34, 1, 0, 0, 0, 0, 0, 0, 252646, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 7298, 0, 50, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [30]:
#Split data training DTL
clf3 = tree.DecisionTreeClassifier()
clf3 = clf3.fit(X_train,Y_train)

# Kinerja DTL
# Akurasi
y_pred = clf3.predict(X_test)
print('Akukrasi =', accuracy_score(Y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred)
print('Confusion Matrix =\n', cm)

Akukrasi = 0.819158735032
Confusion Matrix =
 [[2162  294]
 [ 295  506]]


In [31]:
#Full-training MLP
clf4 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15, 2), random_state=1)
clf4.fit(X_train, Y_train)

# Kinerja MLP
# Akurasi
y_pred = clf4.predict(X_test)
print('Akukrasi =', accuracy_score(Y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(Y_test, y_pred)
print('Confusion Matrix =\n', cm)

Akukrasi = 0.754068160884
Confusion Matrix =
 [[2456    0]
 [ 801    0]]


In [18]:
pd2 = pd.read_csv('censustrain-fnlwgt-country.csv', delimiter=';')
pd2.head()

age  Private  Self-emp-not-inc  Self-emp-inc  Federal-gov  Local-gov  \
0   39        0                 0             0            0          0   
1   50        0                 1             0            0          0   
2   38        1                 0             0            0          0   
3   53        1                 0             0            0          0   
4   28        1                 0             0            0          0   

   State-gov  Without-pay  education-num  Married-civ-spouse   ...    White  \
0          1            0             13                   0   ...        1   
1          0            0             13                   1   ...        1   
2          0            0              9                   0   ...        1   
3          0            0              7                   1   ...        0   
4          0            0             13                   1   ...        0   

   Asian-Pac-Islander  Amer-Indian-Eskimo  Other  Black  sex  capital-gain  \
0                   0                   0      0      0    1          2174   
1                   0                   0      0      0    1             0   
2                   0                   0      0      0    1             0   
3                   0                   0      0      1    1             0   
4                   0                   0      0      1    0             0   

   capital-loss  hours-per-week  income  
0             0              40       0  
1             0              13       0  
2             0              40       0  
3             0              40       0  
4             0              40       0  

[5 rows x 46 columns]

In [19]:
X2 = pd2.iloc[:,0:-1].values.tolist()
print(X2[:5])
Y2 = pd2.iloc[:,-1].values.tolist()
print(Y2[:5])

[[39, 0, 0, 0, 0, 0, 1, 0, 13, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2174, 0, 40], [50, 0, 1, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 13], [38, 1, 0, 0, 0, 0, 0, 0, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 40], [53, 1, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 40], [28, 1, 0, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 40]]
[0, 0, 0, 0, 0]


In [20]:
#Cross validation training DTL
clf5 = tree.DecisionTreeClassifier()
scores = cross_val_score(clf5, X2, Y2, cv=10)
print("Akurasi: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Akurasi: 0.82 (+/- 0.01)


In [21]:
#Cross validation training MLP
clf6 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15, 2), random_state=1)
scores = cross_val_score(clf6, X2, Y2, cv=10)
print("Akurasi: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Akurasi: 0.76 (+/- 0.00)


In [22]:
#Split data 90%/10%
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(X2, Y2, test_size=0.1, random_state=42)
print(X_train2[:5])
print(X_test2[:5])

[[35, 1, 0, 0, 0, 0, 0, 0, 13, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30], [20, 1, 0, 0, 0, 0, 0, 0, 10, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 20], [34, 1, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 40], [34, 1, 0, 0, 0, 0, 0, 0, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 7298, 0, 50], [22, 1, 0, 0, 0, 0, 0, 0, 9, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 22]]
[[27, 1, 0, 0, 0, 0, 0, 0, 10, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 38], [45, 0, 0, 0, 0, 0, 1, 0, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 40], [29, 1, 0, 0, 0, 0

In [23]:
#Split data training DTL
clf7 = tree.DecisionTreeClassifier()
clf7 = clf7.fit(X_train2,Y_train2)

# Kinerja DTL
# Akurasi
y_pred = clf7.predict(X_test2)
print('Akukrasi =', accuracy_score(Y_test2, y_pred))

# Confusion Matrix
cm = confusion_matrix(Y_test2, y_pred)
print('Confusion Matrix =\n', cm)

Akukrasi = 0.832668099478
Confusion Matrix =
 [[2199  257]
 [ 288  513]]


In [24]:
#Full-training MLP
clf8 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15, 2), random_state=1)
clf8.fit(X_train2, Y_train2)

# Kinerja MLP
# Akurasi
y_pred = clf8.predict(X_test2)
print('Akukrasi =', accuracy_score(Y_test2, y_pred))

# Confusion Matrix
cm = confusion_matrix(Y_test2, y_pred)
print('Confusion Matrix =\n', cm)

Akukrasi = 0.754068160884
Confusion Matrix =
 [[2456    0]
 [ 801    0]]
